import {writeFileSync} from 'node:fs'
import {importSearcher, templateSearcher} from "./deps/searchers.js"

const src = `
// generated by ../scrpts/build-regexp.js
// do not edit this manually

export const importSearcher = ${importSearcher}
export const templateSearcher = ${templateSearcher}
`

writeFileSync('./src/searchers.js', src)